import type { Metadata } from "next";
import { headers } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import { optimisticFontVF } from '@/app/fonts';
import "react-phone-input-2/lib/style.css";
import "@/public/styles/checkbox.scss"
import "@/public/styles/custom.css"
import "./globals.css"
import ReduxProvider from "./store/provider";
import LocationBootstrap from "./store/LocationBootstrap";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const isBot = headersList.get('x-is-bot') === 'true';

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${optimisticFontVF.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {isBot ? null : (
          <ReduxProvider>
            <LocationBootstrap />
            {children}
          </ReduxProvider >
        )}
      </body>
    </html>
  );
}
